name: avi-os
description: OS for my Aviture laptop

base-image: ghcr.io/ublue-os/aurora-dx-nvidia
image-version: latest

modules:
  - from-file: base/packages.yml
  - from-file: base/flatpaks.yml
  - from-file: base/fonts.yml
  - from-file: displaylink.yml
  - from-file: nix.yml

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - "mkdir -p /opt"

  - type: signing

